### ISSUE TITLE
Android still crash 

### ISSUE THREAD

**Issue by ponleukea** [classapp/react-native-video-helper#29]
Crash on android OS:
- OS : 9.0
- Device : Huawei Nova 3
- react-native-video-helper : 1.4.4
Here is error log:

   java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:355)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:76)
        at com.reactlibrary.video.MediaController.convertVideo(MediaController.java:252)
        at com.reactlibrary.video.VideoCompress$VideoCompressTask.doInBackground(VideoCompress.java:50)
        at com.reactlibrary.video.VideoCompress$VideoCompressTask.doInBackground(VideoCompress.java:22)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246) 
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784)

**Comment by jaiprakashPal** [comment]
not worked

**Comment by Janviba911** [comment]
@samin 
Please check above issue which is shared by @ponleukea I am also stuck in this

**Comment by RajeshBabu** [comment]
Any update on above crash, I am experiencing the same issue  while using this library.

**Comment by monuv10** [comment]
Any update

**Comment by LozytskyiA** [comment]
Any update
